services:
  - type: web
    name: softnet-technology-academy
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
